### PR TITLE
Add vxlan support

### PR DESCRIPTION
**Pull request by negbie**

### CODE REVIEW

**Comment by dmsf100** [comment]
Hi @negbie. 

Do we need to enable anything to be able to decode VXLAN? I'm trying to setup port mirroring with vxlan encapsulation but it doesn't seem to catch any SIP Packets. When I run heplify. 🤷‍♂️

**Comment by negbie** [comment]
Did you try to run heplify with the -vlan flag?

**Comment by dmsf100** [comment]
I get the following output:

Critical: SetBPFFilter '(tcp or sctp) and greater 42 and portrange 5060-5090 or (udp and greater 128 and portrange 5060-5090 or ip[6:2] & 0x1fff != 0 or ip6[6]=44) or (ip and ip[6] & 0x2 = 0 and ip[6:2] & 0x1fff = 0 and udp and udp[8] & 0xc0 = 0x80 and udp[9] >= 0xc8 && udp[9] <= 0xcc) or (vlan and ((tcp or sctp) and greater 42 and portrange 5060-5090 or (udp and greater 128 and portrange 5060-5090 or ip[6:2] & 0x1fff != 0 or ip6[6]=44) or (ip and ip[6] & 0x2 = 0 and ip[6:2] & 0x1fff = 0 and udp and udp[8] & 0xc0 = 0x80 and udp[9] >= 0xc8 && udp[9] <= 0xcc)))' for pcap: no VLAN support for Linux cooked v1

**Comment by lmangani** [comment]
Wild guess - You cannot use this with `any` interface selector which includes the local interface

**Comment by dmsf100** [comment]
After defining the interface it no longer gives the error. But it still doesn't catch any SIP traffic.
We captured a pcap and the layers are as follows on wireshark (this is an IP in IP packet).

Frame
Linux Cooked Capture v1
Internet Protocol Version 4
User Datagram Protocol
Virtual eXtensible Local Area Network
Ethernet II
Internet Protocol Version 4
User Datagram Protocol
Session Initiation Protocol (INVITE)

**Comment by lmangani** [comment]
IPIP packets are encapsulated and not raw packets hence won't be captured with those settings

**Comment by dmsf100** [comment]
I see. In the code it seems that you go through all the layers and decode them. Would it be possible if we decode IP layer twice?

**Comment by lmangani** [comment]
No, it would need a dedicated switch and handler. Feel free to open a PR with anytime if you want to add this feature. 
We used to support this in HOMER 3/5 a decade ago but I haven't seen IP-in-IP used for a long, long time.

**Comment by dmsf100** [comment]
Well that's what AWS is using for traffic mirroring today.

**Comment by lmangani** [comment]
This might be the case (provide a link?) but none of our (many) AWS customers is using this older method apparently. If you'd like this being discussed, feel free to [open a feature request](https://github.com/sipcapture/homer/issues) with a donation for this to be supported. This issue has already been closed so its not the proper place to discuss this.

**Pull request merged**
