### PR TITLE
Adds Discard uninteresting SIP packets by Destination IP(s) flag

### PR DESCRIPTION
**Pull request by nzspearo**
Adds a new flag to support discarding SIP packets by destination IP(s)

Same logic as already implemented src IP, just adds it for dst IP(s) also

### CODE REVIEW

**Comment by kYroL01** [comment]
Hi @nzspearo Could you please refresh your PR in order to be in sync with `master` ? Thanks

**Comment by nzspearo** [comment]
> Hi @nzspearo Could you please refresh your PR in order to be in sync with `master` ? Thanks

I think this is done now. I've got that CLA issue, I've singed it but it does not seem to be linked to my commits, not sure why.

**Comment by lmangani** [comment]
> > Hi @nzspearo Could you please refresh your PR in order to be in sync with `master` ? Thanks
> 
> I think this is done now. I've got that CLA issue, I've singed it but it does not seem to be linked to my commits, not sure why.

Thanks & sorry about this issue. You're probably using a different git identity or email when signing up the CLA?

**Comment by lmangani** [comment]
CI still failing as follows:

> Error: sniffer/sniffer.go:278:12: cfgMain.HepCollector undefined (type *config.Config has no field or method HepCollector)
Error: sniffer/sniffer.go:279:37: cfgMain.HepCollector undefined (type *config.Config has no field or method HepCollector)
Error: sniffer/sniffer.go:281:35: cfgMain.CollectOnlySip undefined (type *config.Config has no field or method CollectOnlySip)
Error: Process completed with exit code 2.

**Comment by kYroL01** [comment]
@nzspearo your PR was failing because not sync with latest commit in master. I fixed it.
Please try again to sign Contributor License Agreement and we're happy to merge it

**Comment by kYroL01** [comment]
Already implemented here https://github.com/sipcapture/heplify/pull/221
Thanks anyway

**Pull request closed without merging**
